name: NumaAdmin
main: com.github.NUMANUMA.NumaAdmin.NumaAdmin
version: 1.0.1
commands:
  gm:
    description: Change game mode command.
    usage: /gm [0=サバイバル,1=クリエイティブ,2=アドベンチャー]
    permission: numaadmin.gm
    permission-message: You don't have <permission>
  spawn:
    description: スポーン
    usage: /<command>
    permission: numaadmin.spawn
    permission-message: You don't have <permission>
  setspawn:
    description: スポーン設定
    usage: /<command>
    permission: numaadmin.setspawn
    permission-message: You don't have <permission>
  tenki:
    description: 天気変更
    usage: /<command> [hare=晴れ,ame=雨,kaminari=雷雨]
    permission: numaadmin.tenki
    permission-message: You don't have <permission>
  meteo:
    description: メテオ落下
    usage: /<command>
    permission: numaadmin.meteo
    permission-message: You don't have <permission>
  oreevent:
    descripiton: 鉱石イベント開始
    usage: /<command>
    permission: numaadmin.oreevent
    permission-message: You don't have <permission>