name: NumaAdmin
main: com.github.NUMANUMA.NumaAdmin.NumaAdmin
version: 1.0.1
commands:
  gm:
    description: Change game mode command.
    usage: /gm [0=サバイバル,1=クリエイティブ,2=アドベンチャー]
    permission: numaadmin.gm
    permission-message: You don't have <permission>
  aa:
    description: AA表示
    usage: /<command>
    permission: numaadmin.aa
    permission-message: You don't have <permission>
  spawn:
    description: スポーン
    usage: /<command>
    permission: numaadmin.spawn
    permission-message: You don't have <permission>
  setspawn:
    description: スポーン設定
    usage: /<command>
    permission: numaadmin.setspawn
    permission-message: You don't have <permission>